from recipes.machine import Machine
from recipes.module import Module
from recipes.recipe import Recipe


def init_machines():
    return {
        "player":               Machine(1, 0),
        "assembling_machine_1": Machine(.5, 0),
        "assembling_machine_2": Machine(.75, 2),
        "assembling_machine_3": Machine(1.25, 4),
        "chemical_plant":       Machine(1, 3),
        "oil_refinery":         Machine(1, 3),
        "centrifuge":           Machine(1, 2),
        "rocket_silo":          Machine(1, 4),
        "stone_furnace":        Machine(1, 0),
        "steel_furnace":        Machine(2, 0),
        "electric_furnace":     Machine(2, 2),
        "lab":                  Machine(1, 2)
    }


def init_modules():
    return {
        "speed_module_1":        Module(.2, 0),
        "speed_module_2":        Module(.3, 0),
        "speed_module_3":        Module(.5, 0),
        "productivity_module_1": Module(-.15, .04),
        "productivity_module_2": Module(-.15, .06),
        "productivity_module_3": Module(-.15, .1)
    }


def init_recipes():
    any_machine = ["assembling_machine_3", "assembling_machine_2", "assembling_machine_1", "player"]
    non_player = ["assembling_machine_3", "assembling_machine_2", "assembling_machine_1"]
    advanced_machines = ["assembling_machine_3", "assembling_machine_2"]
    furnaces = ["electric_furnace", "steel_furnace", "stone_furnace"]
    return {
        "wooden_chest":                        Recipe([("wood", 2)],
                                                      .5,
                                                      [("wooden_chest", 1, 100)],
                                                      any_machine),
        "iron_chest":                          Recipe([("iron_plate", 8)],
                                                      .5,
                                                      [("iron_chest", 1, 100)],
                                                      any_machine),
        "steel_chest":                         Recipe([("steel_plate", 8)],
                                                      .5,
                                                      [("steel_chest", 1, 100)],
                                                      any_machine),
        "storage_tank":                        Recipe([("iron_plate", 20),
                                                       ("steel_plate", 5)],
                                                      3,
                                                      [("storage_tank", 1, 100)],
                                                      any_machine),
        "transport_belt":                      Recipe([("iron_plate", 1),
                                                       ("iron_gear_wheel", 1)],
                                                      .5,
                                                      [("transport_belt", 2, 100)],
                                                      any_machine),
        "fast_transport_belt":                 Recipe([("iron_gear_wheel", 5),
                                                       ("transport_belt", 1)],
                                                      .5,
                                                      [("fast_transport_belt", 1, 100)],
                                                      any_machine),
        "express_transport_belt":              Recipe([("iron_gear_wheel", 10),
                                                       ("fast_transport_belt", 1),
                                                       ("lubricant", 20)],
                                                      .5,
                                                      [("express_transport_belt", 1, 100)],
                                                      advanced_machines),
        "underground_belt":                    Recipe([("iron_plate", 10),
                                                       ("transport_belt", 5)],
                                                      1,
                                                      [("underground_belt", 2, 100)],
                                                      any_machine),
        "fast_underground_belt":               Recipe([("iron_gear_wheel", 40),
                                                       ("underground_belt", 2)],
                                                      2,
                                                      [("fast_underground_belt", 2, 100)],
                                                      any_machine),
        "express_underground_belt":            Recipe([("iron_gear_wheel", 80),
                                                       ("fast_underground_belt", 2),
                                                       ("lubricant", 40)],
                                                      2,
                                                      [("express_underground_belt", 2, 100)],
                                                      advanced_machines),
        "splitter":                            Recipe([("iron_plate", 5),
                                                       ("electronic_circuit", 5),
                                                       ("transport_belt", 4)],
                                                      1,
                                                      [("splitter", 1, 100)],
                                                      any_machine),
        "fast_splitter":                       Recipe([("iron_gear_wheel", 10),
                                                       ("electronic_circuit", 10),
                                                       ("splitter", 1)],
                                                      2,
                                                      [("fast_splitter", 1, 100)],
                                                      any_machine),
        "express_splitter":                    Recipe([("iron_gear_wheel", 10),
                                                       ("advanced_circuit", 10),
                                                       ("fast_splitter", 1),
                                                       ("lubricant", 80)],
                                                      2,
                                                      [("express_splitter", 1, 100)],
                                                      advanced_machines),
        "burner_inserter":                     Recipe([("iron_plate", 1),
                                                       ("iron_gear_wheel", 1)],
                                                      .5,
                                                      [("burner_inserter", 1, 100)],
                                                      any_machine),
        "inserter":                            Recipe([("iron_plate", 1),
                                                       ("iron_gear_wheel", 1),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("inserter", 1, 100)],
                                                      any_machine),
        "long_handed_inserter":                Recipe([("iron_plate", 1),
                                                       ("iron_gear_wheel", 1),
                                                       ("inserter", 1)],
                                                      .5,
                                                      [("long_handed_inserter", 1, 100)],
                                                      any_machine),
        "fast_inserter":                       Recipe([("iron_plate", 2),
                                                       ("electronic_circuit", 2),
                                                       ("inserter", 1)],
                                                      .5,
                                                      [("fast_inserter", 1, 100)],
                                                      any_machine),
        "filter_inserter":                     Recipe([("electronic_circuit", 4),
                                                       ("fast_inserter", 1)],
                                                      .5,
                                                      [("filter_inserter", 1, 100)],
                                                      any_machine),
        "stack_inserter":                      Recipe([("iron_gear_wheel", 15),
                                                       ("electronic_circuit", 15),
                                                       ("advanced_circuit", 1),
                                                       ("fast_inserter", 1)],
                                                      .5,
                                                      [("stack_inserter", 1, 100)],
                                                      any_machine),
        "stack_filter_inserter":               Recipe([("electronic_circuit", 5),
                                                       ("stack_inserter", 1)],
                                                      .5,
                                                      [("stack_filter_inserter", 1, 100)],
                                                      any_machine),
        "small_electric_pole":                 Recipe([("wood", 1),
                                                       ("copper_cable", 2)],
                                                      .5,
                                                      [("small_electric_pole", 2, 100)],
                                                      any_machine),
        "medium_electric_pole":                Recipe([("copper_plate", 2),
                                                       ("steel_plate", 2),
                                                       ("iron_stick", 4)],
                                                      .5,
                                                      [("medium_electric_pole", 1, 100)],
                                                      any_machine),
        "big_electric_pole":                   Recipe([("copper_plate", 5),
                                                       ("steel_plate", 5),
                                                       ("iron_stick", 8)],
                                                      .5,
                                                      [("big_electric_pole", 1, 100)],
                                                      any_machine),
        "substation":                          Recipe([("copper_plate", 5),
                                                       ("steel_plate", 10),
                                                       ("advanced_circuit", 5)],
                                                      .5,
                                                      [("substation", 1, 100)],
                                                      any_machine),
        "pipe":                                Recipe([("iron_plate", 1)],
                                                      .5,
                                                      [("pipe", 1, 100)],
                                                      any_machine),
        "pipe_to_ground":                      Recipe([("iron_plate", 5),
                                                       ("pipe", 10)],
                                                      .5,
                                                      [("pipe_to_ground", 2, 100)],
                                                      any_machine),
        "pump":                                Recipe([("steel_plate", 1),
                                                       ("engine_unit", 1),
                                                       ("pipe", 1)],
                                                      2,
                                                      [("pump", 1, 100)],
                                                      any_machine),
        "rail":                                Recipe([("stone", 1),
                                                       ("steel_plate", 1),
                                                       ("iron_stick", 1)],
                                                      .5,
                                                      [("rail", 2, 100)],
                                                      any_machine),
        "train_stop":                          Recipe([("iron_plate", 6),
                                                       ("steel_plate", 3),
                                                       ("iron_stick", 6),
                                                       ("electronic_circuit", 5)],
                                                      .5,
                                                      [("train_stop", 1, 100)],
                                                      any_machine),
        "rail_signal":                         Recipe([("iron_plate", 5),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("rail_signal", 1, 100)],
                                                      any_machine),
        "rail_chain_signal":                   Recipe([("iron_plate", 5),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("rail_chain_signal", 1, 100)],
                                                      any_machine),
        "locomotive":                          Recipe([("steel_plate", 30),
                                                       ("electronic_circuit", 10),
                                                       ("engine_unit", 20)],
                                                      4,
                                                      [("locomotive", 1, 100)],
                                                      any_machine),
        "cargo_wagon":                         Recipe([("iron_plate", 20),
                                                       ("steel_plate", 20),
                                                       ("iron_gear_wheel", 10)],
                                                      1,
                                                      [("cargo_wagon", 1, 100)],
                                                      any_machine),
        "fluid_wagon":                         Recipe([("steel_plate", 16),
                                                       ("iron_gear_wheel", 10),
                                                       ("storage_tank", 1),
                                                       ("pipe", 8)],
                                                      1.5,
                                                      [("fluid_wagon", 1, 100)],
                                                      any_machine),
        "artillery_wagon":                     Recipe([("steel_plate", 40),
                                                       ("iron_gear_wheel", 10),
                                                       ("advanced_circuit", 20),
                                                       ("engine_unit", 64),
                                                       ("pipe", 16)],
                                                      4,
                                                      [("artillery_wagon", 1, 100)],
                                                      any_machine),
        "car":                                 Recipe([("iron_plate", 20),
                                                       ("steel_plate", 5),
                                                       ("engine_unit", 8)],
                                                      2,
                                                      [("car", 1, 100)],
                                                      any_machine),
        "tank":                                Recipe([("steel_plate", 50),
                                                       ("iron_gear_wheel", 15),
                                                       ("advanced_circuit", 10),
                                                       ("engine_unit", 32)],
                                                      5,
                                                      [("tank", 1, 100)],
                                                      any_machine),
        "logistic_robot":                      Recipe([("advanced_circuit", 2),
                                                       ("flying_robot_frame", 1)],
                                                      .5,
                                                      [("logistic_robot", 1, 100)],
                                                      any_machine),
        "construction_robot":                  Recipe([("electronic_circuit", 2),
                                                       ("flying_robot_frame", 1)],
                                                      .5,
                                                      [("construction_robot", 1, 100)],
                                                      any_machine),
        "active_provider_chest":               Recipe([("electronic_circuit", 3),
                                                       ("advanced_circuit", 1),
                                                       ("steel_chest", 1)],
                                                      .5,
                                                      [("active_provider_chest", 1, 100)],
                                                      any_machine),
        "passive_provider_chest":              Recipe([("electronic_circuit", 3),
                                                       ("advanced_circuit", 1),
                                                       ("steel_chest", 1)],
                                                      .5,
                                                      [("passive_provider_chest", 1, 100)],
                                                      any_machine),
        "storage_chest":                       Recipe([("electronic_circuit", 3),
                                                       ("advanced_circuit", 1),
                                                       ("steel_chest", 1)],
                                                      .5,
                                                      [("storage_chest", 1, 100)],
                                                      any_machine),
        "buffer_chest":                        Recipe([("electronic_circuit", 3),
                                                       ("advanced_circuit", 1),
                                                       ("steel_chest", 1)],
                                                      .5,
                                                      [("buffer_chest", 1, 100)],
                                                      any_machine),
        "requester_chest":                     Recipe([("electronic_circuit", 3),
                                                       ("advanced_circuit", 1),
                                                       ("steel_chest", 1)],
                                                      .5,
                                                      [("requester_chest", 1, 100)],
                                                      any_machine),
        "roboport":                            Recipe([("steel_plate", 45),
                                                       ("iron_gear_wheel", 45),
                                                       ("advanced_circuit", 45)],
                                                      5,
                                                      [("roboport", 1, 100)],
                                                      any_machine),
        "lamp":                                Recipe([("iron_plate", 1),
                                                       ("copper_cable", 3),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("lamp", 1, 100)],
                                                      any_machine),
        "red_wire":                            Recipe([("copper_cable", 1),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("red_wire", 1, 100)],
                                                      any_machine),
        "green_wire":                          Recipe([("copper_cable", 1),
                                                       ("electronic_circuit", 1)],
                                                      .5,
                                                      [("green_wire", 1, 100)],
                                                      any_machine),
        "arithmetic_combinator":               Recipe([("copper_cable", 5),
                                                       ("electronic_circuit", 5)],
                                                      .5,
                                                      [("arithmetic_combinator", 1, 100)],
                                                      any_machine),
        "decider_combinator":                  Recipe([("copper_cable", 5),
                                                       ("electronic_circuit", 5)],
                                                      .5,
                                                      [("decider_combinator", 1, 100)],
                                                      any_machine),
        "constant_combinator":                 Recipe([("copper_cable", 5),
                                                       ("electronic_circuit", 2)],
                                                      .5,
                                                      [("constant_combinator", 1, 100)],
                                                      any_machine),
        "power_switch":                        Recipe([("iron_plate", 5),
                                                       ("copper_cable", 5),
                                                       ("electronic_circuit", 2)],
                                                      2,
                                                      [("power_switch", 1, 100)],
                                                      any_machine),
        "programmable_speaker":                Recipe([("iron_plate", 3),
                                                       ("copper_cable", 5),
                                                       ("iron_stick", 4),
                                                       ("electronic_circuit", 4)],
                                                      2,
                                                      [("programmable_speaker", 1, 100)],
                                                      any_machine),
        "stone_brick":                         Recipe([("stone", 2)],
                                                      3.2,
                                                      [("stone_brick", 1, 100)],
                                                      furnaces,
                                                      True),
        "concrete":                            Recipe([("iron_ore", 1),
                                                       ("stone_brick", 5),
                                                       ("water", 100)],
                                                      10,
                                                      [("concrete", 10, 100)],
                                                      advanced_machines),
        "hazard_concrete":                     Recipe([("concrete", 10)],
                                                      .25,
                                                      [("hazard_concrete", 10, 100)],
                                                      any_machine),
        "refined_concrete":                    Recipe([("steel_plate", 1),
                                                       ("iron_stick", 8),
                                                       ("concrete", 20),
                                                       ("water", 100)],
                                                      15,
                                                      [("refined_concrete", 10, 100)],
                                                      advanced_machines),
        "refined_hazard_concrete":             Recipe([("refined_concrete", 10)],
                                                      .25,
                                                      [("refined_hazard_concrete", 10, 100)],
                                                      any_machine),
        "landfill":                            Recipe([("stone", 20)],
                                                      .5,
                                                      [("landfill", 1, 100)],
                                                      any_machine),
        "cliff_explosives":                    Recipe([("explosives", 10),
                                                       ("empty_barrel", 1),
                                                       ("grenade", 1)],
                                                      8,
                                                      [("cliff_explosives", 1, 100)],
                                                      any_machine),
        "repair_pack":                         Recipe([("iron_gear_wheel", 2),
                                                       ("electronic_circuit", 2)],
                                                      .5,
                                                      [("repair_pack", 1, 100)],
                                                      any_machine),
        "boiler":                              Recipe([("pipe", 4),
                                                       ("stone_furnace", 1)],
                                                      .5,
                                                      [("boiler", 1, 100)],
                                                      any_machine),
        "steam_engine":                        Recipe([("iron_plate", 10),
                                                       ("iron_gear_wheel", 8),
                                                       ("pipe", 5)],
                                                      .5,
                                                      [("steam_engine", 1, 100)],
                                                      any_machine),
        "steam_turbine":                       Recipe([("copper_plate", 50),
                                                       ("iron_gear_wheel", 50),
                                                       ("pipe", 20)],
                                                      3,
                                                      [("steam_turbine", 1, 100)],
                                                      any_machine),
        "solar_panel":                         Recipe([("copper_plate", 5),
                                                       ("steel_plate", 5),
                                                       ("electronic_circuit", 15)],
                                                      10,
                                                      [("solar_panel", 1, 100)],
                                                      any_machine),
        "accumulator":                         Recipe([("iron_plate", 2),
                                                       ("battery", 5)],
                                                      10,
                                                      [("accumulator", 1, 100)],
                                                      any_machine),
        "nuclear_reactor":                     Recipe([("copper_plate", 500),
                                                       ("steel_plate", 500),
                                                       ("advanced_circuit", 500),
                                                       ("concrete", 500)],
                                                      8,
                                                      [("nuclear_reactor", 1, 100)],
                                                      any_machine),
        "heat_exchanger":                      Recipe([("copper_plate", 100),
                                                       ("steel_plate", 10),
                                                       ("pipe", 10)],
                                                      3,
                                                      [("heat_exchanger", 1, 100)],
                                                      any_machine),
        "heat_pipe":                           Recipe([("copper_plate", 20),
                                                       ("steel_plate", 10)],
                                                      1,
                                                      [("heat_pipe", 1, 100)],
                                                      any_machine),
        "burner_mining_drill":                 Recipe([("iron_plate", 3),
                                                       ("iron_gear_wheel", 3),
                                                       ("stone_furnace", 1)],
                                                      2,
                                                      [("burner_mining_drill", 1, 100)],
                                                      any_machine),
        "electric_mining_drill":               Recipe([("iron_plate", 10),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 3)],
                                                      2,
                                                      [("electric_mining_drill", 1, 100)],
                                                      any_machine),
        "offshore_pump":                       Recipe([("iron_gear_wheel", 1),
                                                       ("electronic_circuit", 2),
                                                       ("pipe", 1)],
                                                      .5,
                                                      [("offshore_pump", 1, 100)],
                                                      any_machine),
        "pumpjack":                            Recipe([("steel_plate", 5),
                                                       ("iron_gear_wheel", 10),
                                                       ("electronic_circuit", 5),
                                                       ("pipe", 10)],
                                                      5,
                                                      [("pumpjack", 1, 100)],
                                                      any_machine),
        "stone_furnace":                       Recipe([("stone", 5)],
                                                      .5,
                                                      [("stone_furnace", 1, 100)],
                                                      any_machine),
        "steel_furnace":                       Recipe([("steel_plate", 6),
                                                       ("stone_brick", 10)],
                                                      3,
                                                      [("steel_furnace", 1, 100)],
                                                      any_machine),
        "electric_furnace":                    Recipe([("steel_plate", 10),
                                                       ("advanced_circuit", 5),
                                                       ("stone_brick", 10)],
                                                      5,
                                                      [("electric_furnace", 1, 100)],
                                                      any_machine),
        "assembling_machine_1":                Recipe([("iron_plate", 9),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 3)],
                                                      .5,
                                                      [("assembling_machine_1", 1, 100)],
                                                      any_machine),
        "assembling_machine_2":                Recipe([("steel_plate", 2),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 3),
                                                       ("assembling_machine_1", 1)],
                                                      .5,
                                                      [("assembling_machine_2", 1, 100)],
                                                      any_machine),
        "assembling_machine_3":                Recipe([("assembling_machine_2", 2),
                                                       ("speed_module", 4)],
                                                      .5,
                                                      [("assembling_machine_3", 1, 100)],
                                                      any_machine),
        "oil_refinery":                        Recipe([("steel_plate", 15),
                                                       ("iron_gear_wheel", 10),
                                                       ("electronic_circuit", 10),
                                                       ("pipe", 10),
                                                       ("stone_brick", 10)],
                                                      8,
                                                      [("oil_refinery", 1, 100)],
                                                      any_machine),
        "chemical_plant":                      Recipe([("steel_plate", 5),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 5),
                                                       ("pipe", 5)],
                                                      5,
                                                      [("chemical_plant", 1, 100)],
                                                      any_machine),
        "centrifuge":                          Recipe([("steel_plate", 50),
                                                       ("iron_gear_wheel", 100),
                                                       ("advanced_circuit", 100),
                                                       ("concrete", 100)],
                                                      4,
                                                      [("centrifuge", 1, 100)],
                                                      any_machine),
        "lab":                                 Recipe([("iron_gear_wheel", 10),
                                                       ("electronic_circuit", 10),
                                                       ("transport_belt", 4)],
                                                      2,
                                                      [("lab", 1, 100)],
                                                      any_machine),
        "beacon":                              Recipe([("steel_plate", 10),
                                                       ("copper_cable", 10),
                                                       ("electronic_circuit", 20),
                                                       ("advanced_circuit", 20)],
                                                      15,
                                                      [("beacon", 1, 100)],
                                                      any_machine),
        "speed_module":                        Recipe([("electronic_circuit", 5),
                                                       ("advanced_circuit", 5)],
                                                      15,
                                                      [("speed_module", 1, 100)],
                                                      any_machine),
        "speed_module_2":                      Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("speed_module", 4)],
                                                      30,
                                                      [("speed_module_2", 1, 100)],
                                                      any_machine),
        "speed_module_3":                      Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("speed_module_2", 5)],
                                                      60,
                                                      [("speed_module_3", 1, 100)],
                                                      any_machine),
        "efficiency_module":                   Recipe([("electronic_circuit", 5),
                                                       ("advanced_circuit", 5)],
                                                      15,
                                                      [("efficiency_module", 1, 100)],
                                                      any_machine),
        "efficiency_module_2":                 Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("efficiency_module", 4)],
                                                      30,
                                                      [("efficiency_module_2", 1, 100)],
                                                      any_machine),
        "efficiency_module_3":                 Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("efficiency_module_2", 5)],
                                                      60,
                                                      [("efficiency_module_3", 1, 100)],
                                                      any_machine),
        "productivity_module":                 Recipe([("electronic_circuit", 5),
                                                       ("advanced_circuit", 5)],
                                                      15,
                                                      [("productivity_module", 1, 100)],
                                                      any_machine),
        "productivity_module_2":               Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("productivity_module", 4)],
                                                      30,
                                                      [("productivity_module_2", 1, 100)],
                                                      any_machine),
        "productivity_module_3":               Recipe([("advanced_circuit", 5),
                                                       ("processing_unit", 5),
                                                       ("productivity_module_2", 5)],
                                                      60,
                                                      [("productivity_module_3", 1, 100)],
                                                      any_machine),
        "sulfuric_acid":                       Recipe([("iron_plate", 1),
                                                       ("sulfur", 5),
                                                       ("water", 100)],
                                                      1,
                                                      [("sulfuric_acid", 50, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "basic_oil_processing":                Recipe([("crude_oil", 100)],
                                                      5,
                                                      [("heavy_oil", 30, 100),
                                                       ("light_oil", 30, 100),
                                                       ("petroleum_gas", 40, 100)],
                                                      ["oil_refinery"],
                                                      True),
        "advanced_oil_processing":             Recipe([("water", 50),
                                                       ("crude_oil", 100)],
                                                      5,
                                                      [("heavy_oil", 10, 100),
                                                       ("light_oil", 45, 100),
                                                       ("petroleum_gas", 55, 100)],
                                                      ["oil_refinery"],
                                                      True),
        "coal_liquefaction":                   Recipe([("coal", 10),
                                                       ("heavy_oil", 25),
                                                       ("steam", 50)],
                                                      5,
                                                      [("heavy_oil", 90, 100),
                                                       ("light_oil", 20, 100),
                                                       ("petroleum_gas", 10, 100)],
                                                      ["oil_refinery"],
                                                      True),
        "heavy_oil_cracking_to_light_oil":     Recipe([("water", 30),
                                                       ("heavy_oil", 40)],
                                                      2,
                                                      [("light_oil", 30, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "light_oil_cracking_to_petroleum_gas": Recipe([("water", 30),
                                                       ("light_oil", 30)],
                                                      2,
                                                      [("petroleum_gas", 20, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "solid_fuel_from_light_oil":           Recipe([("light_oil", 10)],
                                                      2,
                                                      [("solid_fuel", 1, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "solid_fuel_from_petroleum_gas":       Recipe([("petroleum_gas", 20)],
                                                      2,
                                                      [("solid_fuel", 1, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "solid_fuel_from_heavy_oil":           Recipe([("heavy_oil", 20)],
                                                      2,
                                                      [("solid_fuel", 1, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "lubricant":                           Recipe([("heavy_oil", 10)],
                                                      1,
                                                      [("lubricant", 10, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "iron_plate":                          Recipe([("iron_ore", 1)],
                                                      3.2,
                                                      [("iron_plate", 1, 100)],
                                                      furnaces,
                                                      True),
        "copper_plate":                        Recipe([("copper_ore", 1)],
                                                      3.2,
                                                      [("copper_plate", 1, 100)],
                                                      furnaces,
                                                      True),
        "steel_plate":                         Recipe([("iron_plate", 5)],
                                                      16,
                                                      [("steel_plate", 1, 100)],
                                                      furnaces,
                                                      True),
        "plastic_bar":                         Recipe([("coal", 1),
                                                       ("petroleum_gas", 20)],
                                                      1,
                                                      [("plastic_bar", 2, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "sulfur":                              Recipe([("water", 30),
                                                       ("petroleum_gas", 30)],
                                                      1,
                                                      [("sulfur", 2, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "battery":                             Recipe([("iron_plate", 1),
                                                       ("copper_plate", 1),
                                                       ("sulfuric_acid", 20)],
                                                      4,
                                                      [("battery", 1, 100)],
                                                      ["chemical_plant"],
                                                      True),
        "explosives":                          Recipe([("coal", 1),
                                                       ("sulfur", 1),
                                                       ("water", 10)],
                                                      4,
                                                      [("explosives", 2, 100)],
                                                      any_machine,
                                                      True),
        "uranium_processing":                  Recipe([("uranium_ore", 10)],
                                                      12,
                                                      [("uranium_235", 1, .7),
                                                       ("uranium_238", 1, 99)],
                                                      ["centrifuge"],
                                                      True),
        "fill_crude_oil_barrel":               Recipe([("empty_barrel", 1),
                                                       ("crude_oil", 50)],
                                                      .2,
                                                      [("crude_oil_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_heavy_oil_barrel":               Recipe([("empty_barrel", 1),
                                                       ("heavy_oil", 50)],
                                                      .2,
                                                      [("heavy_oil_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_light_oil_barrel":               Recipe([("empty_barrel", 1),
                                                       ("light_oil", 50)],
                                                      .2,
                                                      [("light_oil_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_lubricant_barrel":               Recipe([("empty_barrel", 1),
                                                       ("lubricant", 50)],
                                                      .2,
                                                      [("lubricant_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_petroleum_gas_barrel":           Recipe([("empty_barrel", 1),
                                                       ("petroleum_gas", 50)],
                                                      .2,
                                                      [("petroleum_gas_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_sulfuric_acid_barrel":           Recipe([("empty_barrel", 1),
                                                       ("sulfuric_acid", 50)],
                                                      .2,
                                                      [("sulfuric_acid_barrel", 1, 100)],
                                                      advanced_machines),
        "fill_water_barrel":                   Recipe([("empty_barrel", 1),
                                                       ("water", 50)],
                                                      .2,
                                                      [("water_barrel", 1, 100)],
                                                      advanced_machines),
        "empty_crude_oil_barrel":              Recipe([("crude_oil_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("crude_oil", 50, 100)],
                                                      advanced_machines),
        "empty_heavy_oil_barrel":              Recipe([("heavy_oil_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("heavy_oil", 50, 100)],
                                                      advanced_machines),
        "empty_light_oil_barrel":              Recipe([("light_oil_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("light_oil", 50, 100)],
                                                      advanced_machines),
        "empty_lubricant_barrel":              Recipe([("lubricant_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("lubricant", 50, 100)],
                                                      advanced_machines),
        "empty_petroleum_gas_barrel":          Recipe([("petroleum_gas_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("petroleum_gas", 50, 100)],
                                                      advanced_machines),
        "empty_sulfuric_acid_barrel":          Recipe([("sulfuric_acid_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("sulfuric_acid", 50, 100)],
                                                      advanced_machines),
        "empty_water_barrel":                  Recipe([("water_barrel", 1)],
                                                      .2,
                                                      [("empty_barrel", 1, 100),
                                                       ("water", 50, 100)],
                                                      advanced_machines),
        "copper_cable":                        Recipe([("copper_plate", 1)],
                                                      .5,
                                                      [("copper_cable", 2, 100)],
                                                      any_machine,
                                                      True),
        "iron_stick":                          Recipe([("iron_plate", 1)],
                                                      .5,
                                                      [("iron_stick", 2, 100)],
                                                      any_machine,
                                                      True),
        "iron_gear_wheel":                     Recipe([("iron_plate", 2)],
                                                      .5,
                                                      [("iron_gear_wheel", 1, 100)],
                                                      any_machine,
                                                      True),
        "empty_barrel":                        Recipe([("steel_plate", 1)],
                                                      1,
                                                      [("empty_barrel", 1, 100)],
                                                      any_machine,
                                                      True),
        "electronic_circuit":                  Recipe([("iron_plate", 1),
                                                       ("copper_cable", 3)],
                                                      .5,
                                                      [("electronic_circuit", 1, 100)],
                                                      any_machine,
                                                      True),
        "advanced_circuit":                    Recipe([("plastic_bar", 2),
                                                       ("copper_cable", 4),
                                                       ("electronic_circuit", 2)],
                                                      6,
                                                      [("advanced_circuit", 1, 100)],
                                                      any_machine,
                                                      True),
        "processing_unit":                     Recipe([("electronic_circuit", 20),
                                                       ("advanced_circuit", 2),
                                                       ("sulfuric_acid", 5)],
                                                      10,
                                                      [("processing_unit", 1, 100)],
                                                      advanced_machines,
                                                      True),
        "engine_unit":                         Recipe([("steel_plate", 1),
                                                       ("iron_gear_wheel", 1),
                                                       ("pipe", 2)],
                                                      10,
                                                      [("engine_unit", 1, 100)],
                                                      non_player,
                                                      True),
        "electric_engine_unit":                Recipe([("electronic_circuit", 2),
                                                       ("engine_unit", 1),
                                                       ("lubricant", 15)],
                                                      10,
                                                      [("electric_engine_unit", 1, 100)],
                                                      advanced_machines,
                                                      True),
        "flying_robot_frame":                  Recipe([("steel_plate", 1),
                                                       ("battery", 2),
                                                       ("electronic_circuit", 3),
                                                       ("electric_engine_unit", 1)],
                                                      20,
                                                      [("flying_robot_frame", 1, 100)],
                                                      any_machine,
                                                      True),
        "satellite":                           Recipe([("processing_unit", 100),
                                                       ("low_density_structure", 100),
                                                       ("rocket_fuel", 50),
                                                       ("solar_panel", 100),
                                                       ("accumulator", 100),
                                                       ("radar", 5)],
                                                      5,
                                                      [("satellite", 1, 100)],
                                                      any_machine),
        "rocket_control_unit":                 Recipe([("processing_unit", 1),
                                                       ("speed_module", 1)],
                                                      30,
                                                      [("rocket_control_unit", 1, 100)],
                                                      any_machine,
                                                      True),
        "low_density_structure":               Recipe([("copper_plate", 20),
                                                       ("steel_plate", 2),
                                                       ("plastic_bar", 5)],
                                                      20,
                                                      [("low_density_structure", 1, 100)],
                                                      any_machine,
                                                      True),
        "rocket_fuel":                         Recipe([("solid_fuel", 10)],
                                                      30,
                                                      [("rocket_fuel", 1, 100)],
                                                      any_machine,
                                                      True),
        "nuclear_fuel":                        Recipe([("rocket_fuel", 1),
                                                       ("uranium_235", 1)],
                                                      90,
                                                      [("nuclear_fuel", 1, 100)],
                                                      ["centrifuge"]),
        "uranium_fuel_cell":                   Recipe([("iron_plate", 10),
                                                       ("uranium_235", 1),
                                                       ("uranium_238", 19)],
                                                      10,
                                                      [("uranium_fuel_cell", 10, 100)],
                                                      any_machine,
                                                      True),
        "nuclear_fuel_reprocessing":           Recipe([("used_up_uranium_fuel_cell", 5)],
                                                      60,
                                                      [("uranium_238", 3, 100)],
                                                      ["centrifuge"]),
        "kovarex_enrichment_process":          Recipe([("uranium_235", 40),
                                                       ("uranium_238", 5)],
                                                      60,
                                                      [("uranium_235", 41, 100),
                                                       ("uranium_238", 2, 100)],
                                                      "centrifuge",
                                                      True),
        "automation_science_pack":             Recipe([("copper_plate", 1),
                                                       ("iron_gear_wheel", 1)],
                                                      5,
                                                      [("automation_science_pack", 1, 100)],
                                                      any_machine,
                                                      True),
        "logistic_science_pack":               Recipe([("transport_belt", 1),
                                                       ("inserter", 1)],
                                                      6,
                                                      [("logistic_science_pack", 1, 100)],
                                                      any_machine,
                                                      True),
        "military_science_pack":               Recipe([("piercing_rounds_magazine", 1),
                                                       ("grenade", 1),
                                                       ("wall", 2)],
                                                      10,
                                                      [("military_science_pack", 2, 100)],
                                                      any_machine,
                                                      True),
        "chemical_science_pack":               Recipe([("solid_fuel", 1),
                                                       ("advanced_circuit", 3),
                                                       ("engine_unit", 2)],
                                                      24,
                                                      [("chemical_science_pack", 2, 100)],
                                                      any_machine,
                                                      True),
        "production_science_pack":             Recipe([("rail", 30),
                                                       ("electric_furnace", 1),
                                                       ("productivity_module", 1)],
                                                      21,
                                                      [("productivity_science_pack", 3, 100)],
                                                      any_machine,
                                                      True),
        "utility_science_pack":                Recipe([("processing_unit", 2),
                                                       ("flying_robot_frame", 1),
                                                       ("low_density_structure", 3)],
                                                      21,
                                                      [("utility_science_pack", 3, 100)],
                                                      any_machine,
                                                      True),
        "pistol":                              Recipe([("iron_plate", 5),
                                                       ("copper_plate", 5)],
                                                      5,
                                                      [("pistol", 1, 100)],
                                                      any_machine),
        "submachine_gun":                      Recipe([("iron_plate", 10),
                                                       ("copper_plate", 5),
                                                       ("iron_gear_wheel", 10)],
                                                      10,
                                                      [("submachine_gun", 1, 100)],
                                                      any_machine),
        "shotgun":                             Recipe([("wood", 5),
                                                       ("iron_plate", 15),
                                                       ("copper_plate", 10),
                                                       ("iron_gear_wheel", 5)],
                                                      10,
                                                      [("shotgun", 1, 100)],
                                                      any_machine),
        "combat_shotgun":                      Recipe([("wood", 10),
                                                       ("copper_plate", 10),
                                                       ("steel_plate", 15),
                                                       ("iron_gear_wheel", 5)],
                                                      10,
                                                      [("combat_shotgun", 1, 100)],
                                                      any_machine),
        "rocket_launcher":                     Recipe([("iron_plate", 5),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 5)],
                                                      10,
                                                      [("rocket_launcher", 1, 100)],
                                                      any_machine),
        "flamethrower":                        Recipe([("steel_plate", 5),
                                                       ("iron_gear_wheel", 10)],
                                                      10,
                                                      [("flamethrower", 1, 100)],
                                                      any_machine),
        "landmine":                            Recipe([("steel_plate", 1),
                                                       ("explosives", 2)],
                                                      5,
                                                      [("landmine", 4, 100)],
                                                      any_machine),
        "firearm_magazine":                    Recipe([("iron_plate", 4)],
                                                      1,
                                                      [("firearm_magazine", 1, 100)],
                                                      any_machine),
        "piercing_rounds_magazine":            Recipe([("copper_plate", 5),
                                                       ("steel_plate", 1),
                                                       ("firearm_magazine", 1)],
                                                      3,
                                                      [("piercing_rounds_magazine", 1, 100)],
                                                      any_machine),
        "uranium_rounds_magazine":             Recipe([("uranium_238", 1),
                                                       ("piercing_rounds_magazine", 1)],
                                                      10,
                                                      [("uranium_rounds_magazine", 1, 100)],
                                                      any_machine),
        "shotgun_shells":                      Recipe([("iron_plate", 2),
                                                       ("copper_plate", 2)],
                                                      3,
                                                      [("shotgun_shells", 1, 100)],
                                                      any_machine),
        "piercing_shotgun_shells":             Recipe([("copper_plate", 5),
                                                       ("steel_plate", 2),
                                                       ("shotgun_shells", 2)],
                                                      8,
                                                      [("piercing_shotgun_shells", 1, 100)],
                                                      any_machine),
        "cannon_shell":                        Recipe([("steel_plate", 2),
                                                       ("plastic_bar", 2),
                                                       ("explosives", 1)],
                                                      8,
                                                      [("cannon_shell", 1, 100)],
                                                      any_machine),
        "explosive_cannon_shell":              Recipe([("steel_plate", 2),
                                                       ("plastic_bar", 2),
                                                       ("explosives", 2)],
                                                      8,
                                                      [("explosive_cannon_shell", 1, 100)],
                                                      any_machine),
        "uranium_cannon_shell":                Recipe([("uranium_238", 1),
                                                       ("cannon_shell", 1)],
                                                      12,
                                                      [("uranium_cannon_shell", 1, 100)],
                                                      any_machine),
        "explosive_uranium_cannon_shell":      Recipe([("uranium_238", 1),
                                                       ("explosive_cannon_shell", 1)],
                                                      12,
                                                      [("explosive_uranium_cannon_shell", 1, 100)],
                                                      any_machine),
        "artillery_shell":                     Recipe([("explosives", 8),
                                                       ("explosive_cannon_shell", 4),
                                                       ("radar", 1)],
                                                      15,
                                                      [("artillery_shell", 1, 100)],
                                                      any_machine),
        "rocket":                              Recipe([("iron_plate", 2),
                                                       ("explosives", 1),
                                                       ("electronic_circuit", 1)],
                                                      8,
                                                      [("rocket", 1, 100)],
                                                      any_machine),
        "explosive_rocket":                    Recipe([("explosives", 2),
                                                       ("rocket", 1)],
                                                      8,
                                                      [("explosive_rocket", 1, 100)],
                                                      any_machine),
        "atomic_bomb":                         Recipe([("explosives", 10),
                                                       ("rocket_control_unit", 10),
                                                       ("uranium_235", 30)],
                                                      50,
                                                      [("atomic_bomb", 1, 100)],
                                                      any_machine),
        "flamethrower_ammo":                   Recipe([("steel_plate", 5),
                                                       ("light_oil", 50),
                                                       ("heavy_oil", 50)],
                                                      6,
                                                      [("flamethrower_ammo", 1, 100)],
                                                      any_machine),
        "grenade":                             Recipe([("coal", 10),
                                                       ("iron_plate", 5)],
                                                      8,
                                                      [("grenade", 1, 100)],
                                                      any_machine),
        "cluster_grenade":                     Recipe([("steel_plate", 5),
                                                       ("explosives", 5),
                                                       ("grenade", 7)],
                                                      8,
                                                      [("cluster_grenade", 1, 100)],
                                                      any_machine),
        "poison_capsule":                      Recipe([("coal", 10),
                                                       ("steel_plate", 3),
                                                       ("electronic_circuit", 3)],
                                                      8,
                                                      [("poison_capsule", 1, 100)],
                                                      any_machine),
        "slowdown_capsule":                    Recipe([("coal", 5),
                                                       ("steel_plate", 2),
                                                       ("electronic_circuit", 2)],
                                                      8,
                                                      [("slowdown_capsule", 1, 100)],
                                                      any_machine),
        "defender_capsule":                    Recipe([("iron_gear_wheel", 3),
                                                       ("electronic_circuit", 3),
                                                       ("piercing_rounds_magazine", 3)],
                                                      8,
                                                      [("defender_capsule", 1, 100)],
                                                      any_machine),
        "distractor_capsule":                  Recipe([("advanced_circuit", 3),
                                                       ("defender_capsule", 4)],
                                                      15,
                                                      [("distractor_capsule", 1, 100)],
                                                      any_machine),
        "destroyer_capsule":                   Recipe([("speed_module", 1),
                                                       ("distractor_capsule", 4)],
                                                      15,
                                                      [("destroyer_capsule", 1, 100)],
                                                      any_machine),
        "discharge_defense_remote":            Recipe([("electronic_circuit", 1)],
                                                      .5,
                                                      [("discharge_defense_remote", 1, 100)],
                                                      any_machine),
        "artillery_targeting_remote":          Recipe([("processing_unit", 1),
                                                       ("radar", 1)],
                                                      .5,
                                                      [("artillery_targeting_remote", 1, 100)],
                                                      any_machine),
        "light_armor":                         Recipe([("iron_plate", 40)],
                                                      3,
                                                      [("light_armor", 1, 100)],
                                                      any_machine),
        "heavy_armor":                         Recipe([("copper_plate", 100),
                                                       ("steel_plate", 50)],
                                                      8,
                                                      [("heavy_armor", 1, 100)],
                                                      any_machine),
        "modular_armor":                       Recipe([("steel_plate", 50),
                                                       ("advanced_circuit", 30)],
                                                      15,
                                                      [("modular_armor", 1, 100)],
                                                      any_machine),
        "power_armor":                         Recipe([("steel_plate", 40),
                                                       ("processing_unit", 40),
                                                       ("electric_engine_unit", 20)],
                                                      20,
                                                      [("power_armor", 1, 100)],
                                                      any_machine),
        "power_armor_mk2":                     Recipe([("processing_unit", 60),
                                                       ("electric_engine_unit", 40),
                                                       ("low_density_structure", 30),
                                                       ("speed_module_2", 25),
                                                       ("efficiency_module_2", 25)],
                                                      25,
                                                      [("power_armor_mk2", 1, 100)],
                                                      any_machine),
        "portable_solar_panel":                Recipe([("steel_plate", 5),
                                                       ("advanced_circuit", 2),
                                                       ("solar_panel", 1)],
                                                      10,
                                                      [("portable_solar_panel", 1, 100)],
                                                      any_machine),
        "portable_fusion_reactor":             Recipe([("processing_unit", 200),
                                                       ("low_density_structure", 50)],
                                                      10,
                                                      [("portable_fusion_reactor", 1, 100)],
                                                      any_machine),
        "energy_shield":                       Recipe([("steel_plate", 10),
                                                       ("advanced_circuit", 5)],
                                                      10,
                                                      [("energy_shield", 1, 100)],
                                                      any_machine),
        "energy_shield_mk2":                   Recipe([("processing_unit", 5),
                                                       ("low_density_structure", 5),
                                                       ("energy_shield", 10)],
                                                      10,
                                                      [("energy_shield_mk2", 1, 100)],
                                                      any_machine),
        "personal_battery":                    Recipe([("steel_plate", 10),
                                                       ("battery", 5)],
                                                      10,
                                                      [("personal_battery", 1, 100)],
                                                      any_machine),
        "personal_battery_mk2":                Recipe([("processing_unit", 15),
                                                       ("low_density_structure", 5),
                                                       ("personal_battery", 10)],
                                                      10,
                                                      [("personal_battery_mk2", 1, 100)],
                                                      any_machine),
        "personal_laser_defense":              Recipe([("processing_unit", 20),
                                                       ("low_density_structure", 5),
                                                       ("laser_turret", 5)],
                                                      10,
                                                      [("personal_laser_defense", 1, 100)],
                                                      any_machine),
        "discharge_defense":                   Recipe([("steel_plate", 20),
                                                       ("processing_unit", 5),
                                                       ("laser_turret", 10)],
                                                      10,
                                                      [("discharge_defense", 1, 100)],
                                                      any_machine),
        "belt_immunity_equipment":             Recipe([("steel_plate", 10),
                                                       ("advanced_circuit", 5)],
                                                      10,
                                                      [("belt_immunity_equipment", 1, 100)],
                                                      any_machine),
        "exoskeleton":                         Recipe([("steel_plate", 20),
                                                       ("processing_unit", 10),
                                                       ("electric_engine_unit", 30)],
                                                      10,
                                                      [("exoskeleton", 1, 100)],
                                                      any_machine),
        "personal_roboport":                   Recipe([("steel_plate", 20),
                                                       ("battery", 45),
                                                       ("iron_gear_wheel", 40),
                                                       ("advanced_circuit", 10)],
                                                      10,
                                                      [("personal_roboport", 1, 100)],
                                                      any_machine),
        "personal_roboport_mk2":               Recipe([("processing_unit", 100),
                                                       ("low_density_structure", 20),
                                                       ("personal_roboport", 5)],
                                                      20,
                                                      [("personal_roboport_mk2", 1, 100)],
                                                      any_machine),
        "nightvision":                         Recipe([("steel_plate", 10),
                                                       ("advanced_circuit", 5)],
                                                      10,
                                                      [("nightvision", 1, 100)],
                                                      any_machine),
        "wall":                                Recipe([("stone_brick", 5)],
                                                      .5,
                                                      [("wall", 1, 100)],
                                                      any_machine),
        "gate":                                Recipe([("steel_plate", 2),
                                                       ("electronic_circuit", 2),
                                                       ("wall", 1)],
                                                      .5,
                                                      [("gate", 1, 100)],
                                                      any_machine),
        "gun_turret":                          Recipe([("iron_plate", 20),
                                                       ("copper_plate", 10),
                                                       ("iron_gear_wheel", 10)],
                                                      8,
                                                      [("gun_turret", 1, 100)],
                                                      any_machine),
        "laser_turret":                        Recipe([("steel_plate", 20),
                                                       ("battery", 12),
                                                       ("electronic_circuit", 20)],
                                                      20,
                                                      [("laser_turret", 1, 100)],
                                                      any_machine),
        "flamethrower_turret":                 Recipe([("steel_plate", 30),
                                                       ("iron_gear_wheel", 15),
                                                       ("engine_unit", 5),
                                                       ("pipe", 10)],
                                                      20,
                                                      [("flamethrower_turret", 1, 100)],
                                                      any_machine),
        "artillery_turret":                    Recipe([("steel_plate", 60),
                                                       ("iron_gear_wheel", 40),
                                                       ("advanced_circuit", 20),
                                                       ("concrete", 60)],
                                                      440,
                                                      [("artillery_turret", 1, 100)],
                                                      any_machine),
        "radar":                               Recipe([("iron_plate", 10),
                                                       ("iron_gear_wheel", 5),
                                                       ("electronic_circuit", 5)],
                                                      .5,
                                                      [("radar", 1, 100)],
                                                      any_machine),
        "rocket_silo":                         Recipe([("steel_plate", 1000),
                                                       ("processing_unit", 200),
                                                       ("electric_engine_unit", 200),
                                                       ("pipe", 100),
                                                       ("concrete", 1000)],
                                                      30,
                                                      [("rocket_silo", 1, 100)],
                                                      any_machine),
        "rocket_part":                         Recipe([("rocket_control_unit", 10),
                                                       ("low_density_structure", 10),
                                                       ("rocket_fuel", 10)],
                                                      3,
                                                      [("rocket_part", 1, 100)],
                                                      ["rocket_silo"],
                                                      True),
        "space_science_pack":                  Recipe([("rocket_part", 100),
                                                       ("satellite", 1)],
                                                      60,
                                                      [("space_science_pack", 1000, 100)],
                                                      ["rocket_silo"]),
        "science":                             Recipe([("automation_science_pack", 1),
                                                       ("logistic_science_pack", 1),
                                                       ("military_science_pack", 1),
                                                       ("chemical_science_pack", 1),
                                                       ("production_science_pack", 1),
                                                       ("utility_science_pack", 1),
                                                       ("space_science_pack", 1)],
                                                      60,
                                                      [("science", 1, 100)],
                                                      ["lab"],
                                                      True)
    }
